# Data Sources

Illowsky, B., & Dean, S. (2023). *Introductory Statistics 2e*. OpenStax. <https://openstax.org/books/introductory-statistics-2e/pages/6-introduction>

Vu, J., & Harrington, D. (2020). Introductory statistics for the life and biomedical sciences (1st ed.). OpenIntro. [biostat statistics textbook](https://1drv.ms/b/c/e002ca8c8522705b/IQBV-YZ48EdOR4CDjGYRw5cAASO4MgXNelHfJSpdsDT3GpI?e=gp5aNh)

# Scientific References

Burgos-Sanchez, C., Jones, N. N., Avillion, M., Gibson, S. J., Patel, J. A., Neighbors, J., Zaghi, S., & Camacho, M. (2020). Impact of alcohol consumption on snoring and sleep apnea: A systematic review and meta-analysis. Otolaryngology–Head and Neck Surgery, 163(6), 1078–1086. https://doi.org/10.1177/0194599820931087

Ghasemi, A., & Zahediasl, S. (2012). Normality tests for statistical analysis: A guide for non-statisticians. International Journal of Endocrinology and Metabolism, 10(2), 486–489. https://doi.org/10.5812/ijem.3505

Kim, T. K. (2015). T test as a parametric statistic. Korean Journal of Anesthesiology, 68(6), 540–546. https://doi.org/10.4097/kjae.2015.68.6.540

Schober, P., Boer, C., & Schwarte, L. A. (2018). Correlation coefficients: Appropriate use and interpretation. Anesthesia & Analgesia, 126(5), 1763–1768. https://doi.org/10.1213/ANE.0000000000002864

Whitley, E., & Ball, J. (2002). Statistics review 6: Nonparametric methods. Critical Care, 6(6), 509–513. https://doi.org/10.1186/cc1820
